ProfonySiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ProfonySiteBundle:Page:index }
    requirements:
        _method:  GET
ProfonySiteBundle_about:
    pattern:  /about
    defaults: { _controller: ProfonySiteBundle:Page:about }
    requirements:
        _method:  GET
ProfonySiteBundle_contact:
    pattern:  /contact
    defaults: { _controller: ProfonySiteBundle:Page:contact }
    requirements:
        _method:  GET|POST
ProfonySiteBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: ProfonySiteBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
ProfonySiteBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: ProfonySiteBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+