parameters:
#    profony_site.example.class: Profony\SiteBundle\Example

services:
#    profony_site.example:
#        class: %profony_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    profony_site.twig.extension:
        class: Profony\SiteBundle\Twig\Extensions\ProfonySiteExtension
        tags:
            - { name: twig.extension }